name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  tfsec:
    name: Terraform Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Run tfsec
        run: |
          tfsec terraform/ || true

  trivy:
    name: Docker Image Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Simplified Trivy installation
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Build Docker image
        run: docker build -t devops-app .

      - name: Scan image with Trivy
        run: |
          trivy image --security-checks vuln --severity HIGH,CRITICAL --exit-code 1 devops-app

  deploy:
  name: Deploy to Kubernetes
  runs-on: ubuntu-latest
  needs: [tfsec, trivy]
  steps:
    - uses: actions/checkout@v3

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Set up kubeconfig
      run: |
        echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
        export KUBECONFIG=$PWD/kubeconfig
        kubectl config get-contexts

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/

