name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  tfsec:
    name: Terraform Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install tfsec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
      - name: Run tfsec
        run: |
          tfsec terraform/ || true

  trivy:
    name: Docker Image Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'devops-app'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'
          ignore-unfixed: true

      - name: Build Docker image
        run: docker build -t devops-app .

      - name: Scan image with Trivy
        run: |
          trivy image --security-checks vuln --severity HIGH,CRITICAL --exit-code 1 devops-app

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: [tfsec, trivy]
    steps:
      - uses: actions/checkout@v3
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0
      - name: Set up Kubeconfig
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/
